// src/views/Proposal.vue
<template>
  <div class="max-w-3xl mx-auto p-4">
    <a-card title="提交竞拍提案" class="mb-4">
      <a-form
        :model="formState"
        layout="vertical"
        @finish="handleSubmit"
      >
        <a-form-item
          label="出价金额"
          name="price"
          :rules="[{ required: true, message: '请输入出价金额' }]"
        >
          <a-input-number
            v-model:value="formState.price"
            :min="1"
            style="width: 100%"
            prefix="¥"
          />
        </a-form-item>

        <a-form-item
          label="付款方式"
          name="paymentMethod"
          :rules="[{ required: true, message: '请选择付款方式' }]"
        >
          <a-select v-model:value="formState.paymentMethod">
            <a-select-option value="full">全款</a-select-option>
            <a-select-option value="mortgage">按揭</a-select-option>
          </a-select>
        </a-form-item>

        <a-form-item
          label="计划付款时间"
          name="paymentDate"
          :rules="[{ required: true, message: '请选择计划付款时间' }]"
        >
          <a-date-picker 
            v-model:value="formState.paymentDate"
            style="width: 100%"
          />
        </a-form-item>

        <a-form-item
          label="附加说明"
          name="description"
        >
          <a-textarea 
            v-model:value="formState.description"
            :rows="4"
          />
        </a-form-item>

        <a-form-item
          label="购房资格证明"
          name="qualification"
        >
          <a-upload-dragger
            v-model:fileList="fileList"
            :multiple="true"
            action="/upload"
            @change="handleChange"
          >
            <p class="ant-upload-drag-icon">
              <inbox-outlined />
            </p>
            <p class="ant-upload-text">点击或拖拽文件上传</p>
          </a-upload-dragger>
        </a-form-item>

        <!-- 保证金状态显示 -->
        <a-card class="mb-4">
          <div class="flex justify-between items-center">
            <span>保证金状态</span>
            <span :class="isPaid ? 'text-green-500' : 'text-red-500'">
              {{ isPaid ? '已支付' : '未支付' }}
            </span>
          </div>
        </a-card>

        <a-form-item>
          <a-button type="primary" html-type="submit" block>
            提交提案
          </a-button>
        </a-form-item>
      </a-form>
    </a-card>
  </div>
</template>

<script setup>
import { ref, reactive } from 'vue'
import { useRouter } from 'vue-router'
import { InboxOutlined } from '@ant-design/icons-vue'
import { message, Modal } from 'ant-design-vue'

const router = useRouter()
const isPaid = ref(false)
const fileList = ref([])

const formState = reactive({
  price: undefined,
  paymentMethod: undefined,
  paymentDate: undefined,
  description: '',
})

const handleSubmit = (values) => {
  if (!isPaid.value) {
    Modal.confirm({
      title: '支付保证金',
      content: '点击确认将模拟支付保证金（演示用）',
      onOk: () => {
        isPaid.value = true
        message.success('保证金支付成功')
      },
    })
    return
  }

  message.success('提案提交成功')
  router.push('/auction/1')
}

const handleChange = (info) => {
  const { status } = info.file
  if (status === 'done') {
    message.success(`${info.file.name} 文件上传成功`)
  } else if (status === 'error') {
    message.error(`${info.file.name} 文件上传失败`)
  }
}
</script>

// pages/auction/[id]/proposal.tsx
import { useState } from 'react';
import { useRouter } from 'next/router';
import { Form, Input, Select, DatePicker, Upload, Button, Card, Modal } from 'antd';
import { InboxOutlined } from '@ant-design/icons';

const { Option } = Select;

export default function SubmitProposal() {
  const router = useRouter();
  const { id } = router.query;
  const [form] = Form.useForm();
  const [isPaid, setIsPaid] = useState(false);

  const handleSubmit = async (values: any) => {
    if (!isPaid) {
      Modal.confirm({
        title: '支付保证金',
        content: '点击确认将模拟支付保证金（演示用）',
        onOk: () => {
          setIsPaid(true);
          Modal.success({
            title: '保证金支付成功',
            content: '您可以继续提交提案',
          });
        },
      });
      return;
    }

    // 提交提案
    Modal.success({
      title: '提案提交成功',
      content: '卖家将尽快审核您的提案',
      onOk: () => router.push(`/auction/${id}`),
    });
  };

  return (
    <div className="max-w-3xl mx-auto p-4">
      <Card title="提交竞拍提案" className="mb-4">
        <Form
          form={form}
          layout="vertical"
          onFinish={handleSubmit}
        >
          <Form.Item
            label="出价金额"
            name="price"
            rules={[{ required: true }]}
          >
            <Input prefix="¥" type="number" />
          </Form.Item>

          <Form.Item
            label="付款方式"
            name="paymentMethod"
            rules={[{ required: true }]}
          >
            <Select>
              <Option value="full">全款</Option>
              <Option value="mortgage">按揭</Option>
            </Select>
          </Form.Item>

          <Form.Item
            label="计划付款时间"
            name="paymentDate"
            rules={[{ required: true }]}
          >
            <DatePicker style={{ width: '100%' }} />
          </Form.Item>

          <Form.Item
            label="附加说明"
            name="description"
          >
            <Input.TextArea rows={4} />
          </Form.Item>

          <Form.Item
            label="购房资格证明"
            name="qualification"
          >
            <Upload.Dragger multiple accept=".pdf,.jpg,.png">
              <p className="ant-upload-drag-icon">
                <InboxOutlined />
              </p>
              <p className="ant-upload-text">点击或拖拽文件上传</p>
            </Upload.Dragger>
          </Form.Item>

          {/* 保证金状态显示 */}
          <Card className="mb-4">
            <div className="flex justify-between items-center">
              <span>保证金状态</span>
              <span className={isPaid ? 'text-green-500' : 'text-red-500'}>
                {isPaid ? '已支付' : '未支付'}
              </span>
            </div>
          </Card>

          <Form.Item>
            <Button type="primary" htmlType="submit" block>
              提交提案
            </Button>
          </Form.Item>
        </Form>
      </Card>
    </div>
  );
}
